# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpriteKit Game Skeleton' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpriteKit Game Skeleton

  pod 'Google-Mobile-Ads-SDK'

end
